[package]
name = "piston-starting"
version = "0.1.0"
authors = ["Jarrett P. Locke <jarrett.p.locke@gmail.com>"]
edition = "2018"

[dependencies]
piston = "0.42.0"
piston2d-graphics = "0.30.0"
pistoncore-glutin_window = "0.54.0"
piston2d-opengl_graphics = "0.59.0"